version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/rj
    steps:
      - checkout
      - run: mvn -P ci clean package
      - run: ls
      - store_artifacts:
          path: NightShadeUHC/target/joust.jar
          destination: artifacts
      - add_ssh_keys
      - deploy:
          name: Deploy to servers
          command: |
            ssh -o BatchMode=yes -o StrictHostKeyChecking=no root@vizsla.cc "uptime"
            scp NightShadeUHC/target/UHC.jar root@158.69.121.66:/home/servers/natournament/plugins/joust.jar
            echo "Finished uploading jars!"
