ARENAS:
  Nether1:
    NAME: 'Nether1'
    LOCATIONS:
      SPAWN1: '-81;56;-41'
      SPAWN2: '-128;56;5'
      SPEC: '-131;59;-44'
  Nether2:
    NAME: 'Nether2'
    LOCATIONS:
      SPAWN1: '-143;56;-41'
      SPAWN2: '-190;56;5'
      SPEC: '-140;59;-44'
  Forest1:
    NAME: 'Forest1'
    LOCATIONS:
      SPAWN1: '-143;56;-102'
      SPAWN2: '-190;56;-55'
      SPEC: '-141;59;-105'
  Desert1:
    NAME: 'Desert1'
    LOCATIONS:
      SPAWN1: '-128;56;-163'
      SPAWN2: '-81;56;-116'
      SPEC: '-132;59;-167'
  Desert2:
    NAME: 'Desert2'
    LOCATIONS:
      SPAWN1: '-143;56;-163'
      SPAWN2: '-190;56;-116'
      SPEC: '-140;59;-167;'
  Forest2:
    NAME: 'Forest2'
    LOCATIONS:
      SPAWN1: '-81;56;-102'
      SPAWN2: '-128;56;-55'
      SPEC: '-132;59;-106'